### PR TITLE
Rebased and should be able to auto pull now.

### PR DESCRIPTION
**Pull request by macmoe**
I was able to add the ability to create a tournament, create participants, and delete a tournament. You can also rank your participants. I've also updated the tournament selector view and you can see the participants in a tournament when you flip the tournament card. We still have a lot of work to do. Holla if you can't pull these commits.

### CODE REVIEW

**Comment by macmoe** [comment]
I added some additional content to the app and should did a rebase again. Creating a tournament and being able to edit it, it almost completed, just a few more minor items to do...

**Comment by macmoe** [comment]
I'm a happy clicker and closed and then reopened this pull request... Hehehe...

**Comment by yuric** [comment]
Did you rebase ok? It keeps complaining about your pull request but does not explain why. I am going to read up some more on pull request errors.

**Comment by macmoe** [comment]
Yea, I get the following message after I run 'git rebase':
Current branch master is up to date.

**Pull request merged**
